### PR TITLE
adding a link to an audio book

### PR DESCRIPTION
**Pull request by bitbazuka**

### CODE REVIEW

**Comment by we-do-it-lu** [comment]
Not sure if the Users Manual for The Human Experience is the kind of reference we want to maintain

**Comment by mybonk** [comment]
Cool to play with GitHub anyways :)

**Review by mybonk — APPROVED** [review]
Go go go

**Comment by we-do-it-lu** [comment]
Done

**Review by we-do-it-lu — APPROVED** [review]

**Pull request closed without merging**
